# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-07-23 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentsPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('max_num', models.IntegerField(default=1)),
                ('introduction', models.CharField(max_length=2000)),
                ('policy', models.CharField(max_length=500)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('is_end', models.BooleanField(default=False)),
                ('is_auth', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
