# Generated by Django 3.0.8 on 2020-07-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200728_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='sns_connect_date',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddField(
            model_name='users',
            name='sns_id',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddField(
            model_name='users',
            name='sns_type',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
    ]
